---
image: jdubz/ci-docker-ansible:latest

services:
  - docker:19.03.1-dind

molecule:
  stage: test
  script:
    - pyenv local 3.7.7
    - pip3 install ansible ansible-lint
    - ansible --version
    - molecule test
