---
image:
  name: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/jdubz/molecule-testing:1.0.0

services:
  - name: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:19.03.1-dind
    alias: docker

.molecule:
  stage: test
  cache:
    key:
      files:
        - .tool-versions
    paths:
      - .tox
  script:
    - tox

debian9:
  extends: .molecule
  variables:
    MOLECULE_PLATFORM: debian-stretch
    MOLECULE_IMAGE: debian:stretch-slim

debian10:
  extends: .molecule
  variables:
    MOLECULE_PLATFORM: debian-buster
    MOLEDULE_IMAGE: debian:buster-slim

ubuntu1804:
  extends: .molecule
  variables:
    MOLECULE_PLATFORM: ubuntu-bionic
    MOLEDULE_IMAGE: ubuntu:bionic

ubuntu2004:
  extends: .molecule
  variables:
    MOLECULE_PLATFORM: ubuntu-focal
    MOLEDULE_IMAGE: ubuntu:focal
