---
version: '3'
services:
  test:
    image: jdubz/molecule-testing:1.0.0
    working_dir: /work/ansible-role-gitlab/
    command: tox
    volumes:
      - certs:/certs/client
      - ./:/work/ansible-role-gitlab/
      - .cache:/root/.cache
    depends_on:
      - docker
  docker:
    image: docker:20.10-dind
    privileged: true
    volumes:
      - certs:/certs/client
volumes:
  certs:
