version: '3'
services:
  test:
    image: jdubz/molecule-testing:1.0.0
    working_dir: /work/ansible-role-gitlab/
    command: tox
    volumes:
      - certs:/certs/client
      - ./:/work/ansible-role-gitlab/
      - .cache:/root/.cache
    depends_on:
      - docker
    networks:
      - default
      - gitlab-docker
  docker:
    image: docker:20.10-dind
    privileged: yes
    # ports:
    #   - 2375:2375
    volumes:
      - certs:/certs/client
    networks:
      - default
      - gitlab-docker
volumes:
  certs:
networks:
  gitlab-docker:
    internal: true
