---
- name: ensure GitLab SSL directory exists
  file:
    path: /etc/gitlab/ssl
    state: directory
    owner: root
    group: root
    mode: 0700

- name: ensure the DH params are generated
  command: "openssl dhparam -out {{ gitlab_nginx_ssl_dhparam }} 2048"
  args:
    creates: "{{ gitlab_nginx_ssl_dhparam }}"

- name: ensure self-signed GitLab certificate exists
  command: >
    openssl req -new -nodes -x509
    -subj "{{ gitlab_nginx_self_signed_cert_subject }}"
    -days 3650 -keyout {{ gitlab_nginx_ssl_certificate_key }}
    -out {{ gitlab_nginx_ssl_certificate }}
    -extensions v3_ca
  args:
    creates: "{{ gitlab_nginx_ssl_certificate }}"
  when: gitlab_nginx_create_self_signed_cert | bool

- name: ensure GitLab is configured
  template:
    src: "{{ gitlab_configuration_template }}"
    dest: "/etc/gitlab/gitlab.rb"
    owner: root
    group: root
    mode: 0600
  notify: reconfigure Gitlab

- name: ensure daily backups are configured
  template:
    src: etc/cron.daily/gitlab.j2
    dest: /etc/cron.daily/gitlab
    owner: root
    group: root
    mode: 0700
  when: gitlab_backups_enabled | bool
  tags:
    - gitlab
    - backup
