---
- name: ensure GitLab dependencies are installed
  package:
    name: "{{ dubzland_gitlab_prerequisites }}"
    state: present

- when: ansible_os_family == 'Debian'
  block:
    - name: check to see if GitLab is installed
      stat:
        path: /usr/bin/gitlab-ctl
      register: gitlab_exec

    - name: get the currently installed GitLab version
      shell: "gitlab-rake gitlab:env:info | grep -A 1 GitLab\ information | grep Version | tr -s ' ' | cut -d' ' -f 2"
      register: _current_gitlab_version
      when: gitlab_exec.stat.exists

    - name: dump the currently install GitLab version
      debug:
        var: _current_gitlab_version

    - name: set the GitLab package url
      set_fact:
        dubzland_gitlab_download_url: "https://packages.gitlab.com/gitlab/gitlab-ee/packages/{{ ansible_distribution }}/{{ ansible_distribution_release }}/gitlab-ee_{{ dubzland_gitlab_version }}-ee.0_amd64.deb/download.deb"

    - name: ensure the correct package is downloaded
      get_url:
        url: "{{ dubzland_gitlab_download_url }}"
        dest: /tmp/gitlab-ee_{{ dubzland_gitlab_version }}-ee.0_amd64.deb

    - name: ensure GitLab is installed
      apt:
        deb: "/tmp/gitlab-ee_{{ dubzland_gitlab_version }}-ee.0_amd64.deb"
      when: dubzland_gitlab_version | length > 0
      notify: start GitLab omnibus
