---
- name: ensure GitLab dependencies are installed
  package:
    name: "{{ gitlab_prerequisites }}"
    state: present

- when: ansible_os_family == 'Debian'
  block:
    - name: check to see if GitLab is installed
      stat:
        path: /usr/bin/gitlab-ctl
      register: gitlab_exec

    - name: ensure the repository installation script exists
      get_url:
        url: "{{ gitlab_repository_installation_script_url }}"
        dest: /tmp/install_gitlab_repository.sh
      when: not gitlab_exec.stat.exists

    - name: ensure the Gitlab repository is installed
      command: bash /tmp/install_gitlab_repository.sh
      when: not gitlab_exec.stat.exists

    - name: ensure the Gitlab package name is defined
      set_fact:
        gitlab_package_name: "{{ gitlab_edition }}={{ gitlab_version }}-{{ gitlab_edition.split('-') | last }}.0"
      when: gitlab_version | default(false)

    - name: ensure the correct Gitlab package is installed
      package:
        name: "{{ gitlab_package_name | default(gitlab_edition) }}"
        state: present
      async: 300
      poll: 5
      when: not gitlab_exec.stat.exists
      notify: reconfigure Gitlab
