---
- name: ensure GitLab dependencies are installed
  package:
    name: "{{ dubzland_gitlab_prerequisites }}"
    state: present

- when: ansible_os_family == 'Debian'
  block:
    - name: check to see if GitLab is installed
      stat:
        path: /usr/bin/gitlab-ctl
      register: gitlab_exec

    - name: ensure the correct package is downloaded
      get_url:
        url: "{{ dubzland_gitlab_download_url }}"
        dest: /tmp/gitlab-ee_{{ dubzland_gitlab_version }}-ee.0_amd64.deb
      when: not gitlab_exec.stat.exists

    - name: ensure GitLab is installed
      apt:
        deb: "/tmp/gitlab-ee_{{ dubzland_gitlab_version }}-ee.0_amd64.deb"
      when: not gitlab_exec.stat.exists
      notify: start GitLab omnibus
