---
- name: ensure GitLab dependencies are installed
  package:
    name: "{{ dubzland_gitlab_prerequisites }}"
    state: present
  tags:
    - gitlab

- when: ansible_os_family == 'Debian'
  block:
    - name: check to see if GitLab is installed
      stat:
        path: /usr/bin/gitlab-ctl
      register: gitlab_exec
      tags:
        - gitlab

    - name: ensure GitLab repo installation script is present
      get_url:
        url: "{{ dubzland_gitlab_install_script }}"
        dest: /tmp/gitlab_repo_install.sh
      when: not gitlab_exec.stat.exists
      tags:
        - gitlab

    - name: ensure the GitLab repo is installed
      command: bash /tmp/gitlab_repo_install.sh
      when: not gitlab_exec.stat.exists
      tags:
        - gitlab

    - name: set the GitLab package name
      set_fact:
        # yamllint disable-line rule:line-length
        dubzland_gitlab_package_name: "{{ dubzland_gitlab_edition }}={{ dubzland_gitlab_version }}"
      when: dubzland_gitlab_version | length > 0

- name: ensure GitLab is installed
  package:
    # yamllint disable-line rule:line-length
    name: "{{ dubzland_gitlab_package_name | default(dubzland_gitlab_edition) }}"
    state: present
  notify: start GitLab omnibus
  tags:
    - gitlab
