---
- name: ensure packages incompatible with GitLab are not present
  package:
    name: "{{ dubzland_gitlab_conflicting_packages }}"
    state: absent
  tags:
    - gitlab

- name: ensure GitLab dependencies are installed
  package:
    name: "{{ dubzland_gitlab_prerequisites }}"
    state: present
  tags:
    - gitlab
