---
- name: Converge
  hosts: all
  pre_tasks:
    - name: update package cache
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'
      changed_when: False

  roles:
    - role: dubzland-gitlab
